<template>
  <Layout>
    <h1>Color</h1>

    <template #palette>
      <h2>Palette</h2>
      <p>
        Particles CSS provides a default color palette that you can use for any
        of the CSS properties that apply a color (color, background-color,
        border-color, etc).
      </p>
      <p>
        The classes will change between CSS properties, but the format for the
        colors will be the same: [class]-[color]-[variant 1-9].
      </p>
      <p>For example: <code>color-purple-5</code></p>
      <p>Here's all the colors generated by default.</p>
      <template
        v-for="color in [
          'red',
          'orange',
          'yellow',
          'green',
          'cyan',
          'blue',
          'purple',
          'pink',
          'gray'
        ]"
      >
        <h5 :key="`${color}-title`" class="span-full m-0 capitalize">
          {{ color }}
        </h5>
        <div :key="`${color}-swatch`" class="grid columns-3 gap-4 mb-2">
          <div
            v-for="num in 9"
            :key="num"
            :class="[`bg-${color}-${num} p-2`, { 'color-white': num > 5 }]"
          >
            {{ `${color}-${num}` }}
          </div>
        </div>
      </template>

      <h4>Customization:</h4>
      <PTable
        :headers="['Variable', 'Default Value']"
        :values="{
          $saturation: '70%',
          $colors: `('red', 0[, $saturation]), ('orange', 25[, $saturation]), ('yellow', 55[, $saturation]), ('green', 110[, $saturation]), ('cyan', 170[, $saturation]), ('blue', 210[, $saturation]), ('purple', 270[, $saturation]), ('pink', 300[, $saturation])`
        }"
      />
      <p>
        Colors use HSL values to dynamically generate variants based on their
        lightness. To accomplish this, you must provide a list of colors. Each
        item in the list must be itself, a lit with the name you want to give
        the color, and it's hue. Optionally, you may provide a third value to
        the color list for it's saturation.
      </p>
      <p>
        To find the right hue from a different color format, try
        <a href="https://convertacolor.com/">this tool</a>.
      </p>
    </template>

    <template #classes>
      <h2>Classes</h2>
      <PTable
        :headers="['Class', 'Properties']"
        :values="{
          '.color-white': 'color: #fff;',
          '.color-black': 'color: #000;',
          '.color-transparent': 'color: transparent;',
          '.color-gray-{1-9}': 'color: {hsl value};',
          '.color-{name}-{1-9}': 'color: {hsl value};'
        }"
      />
    </template>

    <template #color>
      <h2>Color</h2>
      <PExample
        :html="
          `<div class=&quot;color-white bg-black&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-black&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-transparent&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-gray-5&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-red-5&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-orange-5&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-yellow-5&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-green-5&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-cyan-5&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-blue-5&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-purple-5&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-pink-5&quot;>Somewhere, something incredible is waiting to be known.</div>`
        "
      />

      <p>Different lightness</p>
      <PExample
        :html="
          `<div class=&quot;color-purple-1&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-purple-2&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-purple-3&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-purple-4&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-purple-5&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-purple-6&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-purple-7&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-purple-8&quot;>Somewhere, something incredible is waiting to be known.</div>
<div class=&quot;color-purple-9&quot;>Somewhere, something incredible is waiting to be known.</div>`
        "
      />
    </template>
  </Layout>
</template>

